name: foundation_school
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  google_sign_in: ^7.1.0
  google_generative_ai: ^0.4.7
  provider: ^6.1.5
  fl_chart: ^1.0.0
  intl: ^0.20.2
  google_mobile_ads: ^6.0.0
  share_plus: ^11.0.0
  permission_handler: ^12.0.1
  csv: ^6.0.0
  encrypt: ^5.0.3
  google_fonts: ^6.2.1
  crypto: ^3.0.3
  flutter_launcher_icons: ^0.13.1
  mobile_scanner: ^7.0.1
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  flutter_gemini: ^3.0.0
  qr_flutter: ^4.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_tts: ^4.2.3
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/app-icon.png
    - assets/images/
    - assets/audio/
    - assets/data/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app-icon.png"  # Path to your 1024x1024 logo